version: '3'
services:
  nextjs:
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Asian/Seoul
    build:
      context: .
      dockerfile: ./dockerfile

      
