version: '3'
services:
  nodejs:
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - TZ=Asia/Seoul
    build:
      context: .
      dockerfile: ./dockerfile

      
